mongo_URI = "mongodb+srv://darvilek:rP4BqX60cGHfgSSn@cluster0.pmmaiee.mongodb.net/?retryWrites=true&w=majority&tls=true"
db_name = "Recado_Database"
users_collection = "Users_collection"
recados_collection = "Recados_collection"
chats_collection = "Chats_collection"
